name: "redis2"
namespace: guestbook2
deployment:
  image: "redis"
  tag: "1.0.1"
  name: redis-leader2
  replicas: 1



replicaCount: 1


service:
  type: ClusterIP
  port: 6379
  name: redis-leader2

follower:
  name: redis-follower2