# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.follower.name}}
  {{- if .Values }}
  namespace: {{ .Values.namespace | default "default" | quote}}
  {{- end}}
  labels:
    app: {{.Values.name}}
    role: follower
    tier: backend
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.name}}
  template:
    metadata:
        annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        labels:
            app: {{.Values.name}}
            role: follower
            tier: backend
    spec:
      containers:
      - name: follower
        image: gcr.io/google_samples/gb-redis-follower:v2
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
