# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  {{- if .Values }}
  namespace: {{ .Values.namespace | default "default" | quote}}
  {{- end}}
  name: {{.Values.service.name}}
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  ports:
  - port: {{.Values.service.port}}
    targetPort: {{.Values.service.port}}
  selector:
    app: redis
    role: leader
    tier: backend
